trigger: 
  - main

pool: 
  vmImage: 'ubuntu-latest'


steps: 
  - task: Npm@1
    inputs:
      command: "install"
    displayName: "Installing dependencies"
  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: 'run test'
    displayName: "Testing App"
  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: 'run build'
    displayName: "Build Angular App"